FROM python:3.8-alpine

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install -r requirements.txt && \
    pip install -r requirements-dev.txt

COPY snyk_npm_test snyk_npm_test
COPY tests tests

CMD ["pytest", "-p", "no:warnings", "tests"]
